name: run-tests

on: [push, pull_request]

jobs:
    tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
                  coverage: none

            - name: Run composer install
              run: composer install -n --prefer-dist

            - name: Prepare Laravel Application
              run: |
                  cp .env.ci .env
                  php artisan key:generate

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Build frontend assets
              run: npm run build

            - name: Run tests
              run: php artisan test

            # This uses a repository secret that needs to be defined in GitHub
            - name: Deploy staging
              if: github.ref == 'refs/heads/paraloom-staging'
              run: curl "${{ secrets.FORGE_DEPLOY_URL }}"
